### ISSUE TITLE
selfState isn't synced with the renderer on client side

### ISSUE THREAD

**Issue by CoolandonRS** [CoolandonRS/numra-tech#9]
Pertaining to #5
When `ConeyorBasicBlockEntityRender` calls `ConveyorBasicBlockEntity.getSelfState()` it always gets the value of the initial BlockState of the linked `ConveyorBasicBlock` despite the block entity displaying it recognizes the change in scenarios such as changing `ACTIVE`. This prevents any corners from rendering as they should, along with any other `DIRECTION` change. `ACTIVE` changes do not affect this as all of that data is handled in the BlockEntity itself, and the Renderer gets that value through `ConveyorBasicBlockEntity.getProgress(int index)`, which syncs as intended. Currently creating a conveyor immediately as a corner through a command like `setblock ~ ~ ~ numra:conveyor_wood[facing=north_west]` will allow the renderer to use the corner's expected functionality, however changing it to a straight conveyor or a different turn will continue using the first state's rendering method.

Also, the item renderer still seems to only begin rendering the item on an `ACTIVE` change (haven't tested `DIRECTION`) however it now does handle the item rendering correctly thanks to #8
Since this is a similar issue, hopefully @ilcheese2 might be able to help, but otherwise I'll try to work on this when I have time.

**Comment by ilcheese2** [comment]
I think you can use be.getchachedstate or something like that.

**Comment by CoolandonRS** [comment]
> I think you can use be.getchachedstate or something like that.

Well thanks so much! Only downside is that it means `selfState` has been obsolete this entire time. Oh well.

**Comment by CoolandonRS** [comment]
Closed by #10
